INSERT OR IGNORE INTO politicians (id, slug, name, office_held, party, district_state, time_in_office, region_level, photo_url) VALUES 
('pol_f001', 'joe-biden', 'Joe Biden', 'President of the United States', 'Democrat', 'USA', '3 Years', 'Federal', 'https://upload.wikimedia.org/wikipedia/commons/6/68/Joe_Biden_presidential_portrait.jpg'),
('pol_f002', 'kamala-harris', 'Kamala Harris', 'Vice President', 'Democrat', 'USA', '3 Years', 'Federal', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Kamala_Harris_Vice_Presidential_Portrait.jpg'),
('pol_f003', 'donald-trump', 'Donald Trump', 'Former President', 'Republican', 'USA', '4 Years (Past)', 'Federal', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg'),
('pol_f004', 'chuck-schumer', 'Chuck Schumer', 'Senate Majority Leader', 'Democrat', 'NY', '25+ Years', 'Federal', NULL),
('pol_f005', 'mitch-mcconnell', 'Mitch McConnell', 'Senate Minority Leader', 'Republican', 'KY', '30+ Years', 'Federal', NULL),
('pol_f006', 'mikr-johnson', 'Mike Johnson', 'Speaker of the House', 'Republican', 'LA', '7 Years', 'Federal', NULL),
('pol_f007', 'hakeem-jeffries', 'Hakeem Jeffries', 'House Minority Leader', 'Democrat', 'NY', '11 Years', 'Federal', NULL),
('pol_f008', 'bernie-sanders', 'Bernie Sanders', 'U.S. Senate', 'Independent', 'VT', '17 Years', 'Federal', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Bernie_Sanders.jpg'),
('pol_f009', 'ted-cruz', 'Ted Cruz', 'U.S. Senate', 'Republican', 'TX', '11 Years', 'Federal', NULL),
('pol_f010', 'alexandria-ocasio-cortez', 'Alexandria Ocasio-Cortez', 'U.S. House', 'Democrat', 'NY-14', '5 Years', 'Federal', NULL),
('pol_f011', 'marjorie-taylor-greene', 'Marjorie Taylor Greene', 'U.S. House', 'Republican', 'GA-14', '3 Years', 'Federal', NULL),
('pol_f012', 'elizabeth-warren', 'Elizabeth Warren', 'U.S. Senate', 'Democrat', 'MA', '11 Years', 'Federal', NULL),
('pol_f013', 'lindsey-graham', 'Lindsey Graham', 'U.S. Senate', 'Republican', 'SC', '21 Years', 'Federal', NULL),
('pol_f014', 'cory-booker', 'Cory Booker', 'U.S. Senate', 'Democrat', 'NJ', '10 Years', 'Federal', NULL),
('pol_f015', 'josh-hawley', 'Josh Hawley', 'U.S. Senate', 'Republican', 'MO', '5 Years', 'Federal', NULL),
('pol_s001', 'gavin-newsom', 'Gavin Newsom', 'Governor', 'Democrat', 'CA', '5 Years', 'State', 'https://upload.wikimedia.org/wikipedia/commons/7/73/Gavin_Newsom_2023.jpg'),
('pol_s002', 'ron-desantis', 'Ron DeSantis', 'Governor', 'Republican', 'FL', '5 Years', 'State', NULL),
('pol_s003', 'gretchen-whitmer', 'Gretchen Whitmer', 'Governor', 'Democrat', 'MI', '5 Years', 'State', NULL),
('pol_s004', 'greg-abbott', 'Greg Abbott', 'Governor', 'Republican', 'TX', '9 Years', 'State', NULL),
('pol_s005', 'kathy-hochul', 'Kathy Hochul', 'Governor', 'Democrat', 'NY', '2 Years', 'State', NULL),
('pol_s006', 'brian-kemp', 'Brian Kemp', 'Governor', 'Republican', 'GA', '5 Years', 'State', NULL),
('pol_s007', 'jb-pritzker', 'J.B. Pritzker', 'Governor', 'Democrat', 'IL', '5 Years', 'State', NULL),
('pol_s008', 'glenn-youngkin', 'Glenn Youngkin', 'Governor', 'Republican', 'VA', '2 Years', 'State', NULL),
('pol_l001', 'eric-adams', 'Eric Adams', 'Mayor', 'Democrat', 'New York City', '2 Years', 'Local', NULL),
('pol_l002', 'london-breed', 'London Breed', 'Mayor', 'Democrat', 'San Francisco', '5 Years', 'Local', NULL),
('pol_l003', 'karen-bass', 'Karen Bass', 'Mayor', 'Democrat', 'Los Angeles', '1 Year', 'Local', NULL),
('pol_l004', 'brandon-johnson', 'Brandon Johnson', 'Mayor', 'Democrat', 'Chicago', '1 Year', 'Local', NULL);

INSERT OR IGNORE INTO claims (id, politician_id, type, content, date, context) VALUES
('clm_1', 'pol_f001', 'Promise', 'I will support widespread infrastructure renewal across America.', '2020-08-14', 'Campaign Speech'),
('clm_2', 'pol_f003', 'Promise', 'We will build the largest border wall in history.', '2016-06-15', 'Rally'),
('clm_3', 'pol_f008', 'Opinion', 'Healthcare is a human right, not a privilege.', '2019-10-01', 'Debate'),
('clm_4', 'pol_s001', 'Fact', 'California has generated a surplus of $97 billion.', '2022-05-13', 'Budget Revision'),
('clm_5', 'pol_s002', 'Fact', 'Florida''s tourism numbers have exceeded pre-pandemic levels.', '2023-01-22', 'Press Release');
