import { Suspense } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Clock, MapPin } from 'lucide-react';

// mockData.ts (Inline for now)
const newsMatrix = {
  // activeLayout is now computed dynamically rather than hardcoded
  leadStory: {
    title: "Audit Reveals $4.2B in Misallocated Infrastructure Funds Across Three States",
    desk: "Investigation",
    location: "Washington D.C.",
    author: "The Borg Syndicate",
    readTime: "6 min read",
    excerpt: "A comprehensive review of the 2024 Interstate Commerce Grant allocations has uncovered severe discrepancies. Official records cross-referenced with vendor payment registries indicate that billions have been diverted from bridge repair projects into untracked municipal discretionary funds.",
    slug: "audit-reveals-4-2b-misallocated-funds",
    image: "[Hero Image Generated by Gemini 3.1 Flash]",
    // Algorithmic Drivers:
    severity: 3,             // 1-5 scale. 5 forces Hero Layout.
    hasHighResHero: true,    // True if AI generated a high quality 21:9 image
  },
  secondaryStories: [
    {
      title: "Senate Appropriations Committee Clashes Over Defense Budget Allocations",
      desk: "Politics",
      timeAgo: "2 hours ago",
      excerpt: "Hours of testimony revealed deep partisan divides on modernization priorities, with specific focus on maritime autonomous systems...",
      slug: "senate-hearing-transcripts"
    },
    {
      title: "Market Recovers Sharply Following CPI Data Release",
      desk: "Economy",
      timeAgo: "3 hours ago",
      excerpt: "Core inflation met expectations, cooling fears of an aggressive rate hike in the upcoming FOMC meeting...",
      slug: "market-recovers-cpi"
    },
    {
      title: "Federal Reserve Signals Cautious Approach to Interest Rate Adjustments in 2026",
      desk: "Economy",
      timeAgo: "7:15 AM",
      readTime: "8 min",
      excerpt: "In a closely watched statement, the Federal Reserve indicated it will maintain its current policy stance, citing mixed economic signals and...",
      slug: "fed-signals-cautious-approach"
    },
    {
      title: "NASA's Artemis IV Mission Successfully Deploys Lunar Gateway Module",
      desk: "Space",
      timeAgo: "5:15 AM",
      readTime: "5 min",
      excerpt: "The first habitable module of the Lunar Gateway was deployed into orbit around the Moon, marking a critical milestone in humanity's return to...",
      slug: "nasa-artemis-4-gateway"
    },
    {
      title: "Major Cybercrime Ring Dismantled in Multi-Agency Operation Spanning 12 Countries",
      desk: "Investigations",
      timeAgo: "4:20 AM",
      readTime: "7 min",
      excerpt: "Law enforcement agencies across three continents coordinated to arrest 47 suspects tied to a sophisticated ransomware network responsible for...",
      slug: "cybercrime-ring-dismantled"
    }
  ]
};

// Layout A: Standard 3-Column Newspaper (Original)
function StandardNewspaperLayout({ data }: { data: typeof newsMatrix }) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 relative">
      {/* Left Column - Secondary Stories (col-span-3) */}
      <div className="lg:col-span-3 flex flex-col gap-6 order-2 lg:order-1 border-r-0 lg:border-r border-border pr-0 lg:pr-6">
        <div className="border-b-4 border-foreground pb-2 mb-2">
          <h2 className="font-sans uppercase font-bold text-sm tracking-wider">National Desk</h2>
        </div>

        {data.secondaryStories.slice(0, 2).map((story, idx) => (
          <article key={idx} className="border-b border-border pb-6 flex flex-col gap-2">
            <span className={`uppercase text-[10px] font-bold tracking-wider ${story.desk === 'Politics' ? 'text-desk-politics' : 'text-desk-business'}`}>{story.desk}</span>
            <h3 className="font-serif font-bold text-xl leading-tight hover:underline cursor-pointer">
              <Link href={`/${story.desk.toLowerCase()}/${story.slug}`}>
                {story.title}
              </Link>
            </h3>
            <p className="text-sm text-muted-foreground line-clamp-3">
              {story.excerpt}
            </p>
            <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground font-sans">
              <Clock className="w-3 h-3" />
              <span>{story.timeAgo}</span>
            </div>
          </article>
        ))}
      </div>

      {/* Center Column - Lead Story (col-span-6) */}
      <div className="lg:col-span-6 flex flex-col gap-4 border-r-0 lg:border-r border-border pr-0 lg:pr-6 order-1 lg:order-2">
        <article className="flex flex-col gap-4">
          <div className="bg-muted aspect-[16/10] w-full relative overflow-hidden group">
            <div className="absolute inset-0 flex items-center justify-center text-muted-foreground/50">
              {data.leadStory.image}
            </div>
          </div>

          <div className="flex flex-col gap-3 px-2">
            <div className="flex items-center gap-3">
              <span className="bg-desk-borg text-primary-foreground px-2 py-0.5 text-[10px] uppercase tracking-wider font-bold">{data.leadStory.desk}</span>
              <span className="text-muted-foreground text-xs font-sans flex items-center gap-1">
                <MapPin className="w-3 h-3" /> {data.leadStory.location}
              </span>
            </div>

            <h2 className="font-[family-name:var(--font-playfair)] font-black text-4xl md:text-5xl leading-tight tracking-tight hover:text-primary transition-colors cursor-pointer">
              <Link href={`/${data.leadStory.desk.toLowerCase()}/${data.leadStory.slug}`}>
                {data.leadStory.title}
              </Link>
            </h2>

            <div className="flex items-center gap-2 mt-1 mb-2">
              <div className="text-sm font-sans">By <span className="font-bold">{data.leadStory.author}</span></div>
              <span className="text-muted-foreground mx-1">•</span>
              <span className="text-sm text-muted-foreground font-sans">{data.leadStory.readTime}</span>
            </div>

            <p className="text-lg text-foreground/80 leading-relaxed font-serif">
              {data.leadStory.excerpt}
            </p>
          </div>
        </article>
      </div>

      {/* Right Column - Borg Record & Newsletter (col-span-3) */}
      <div className="lg:col-span-3 flex flex-col gap-6 order-3">
        <BorgRecordSidebar />
        <NewsletterSidebar />
      </div>
    </div>
  );
}

// Layout B: Hero Focus (2-Column, huge image left)
function HeroFocusLayout({ data }: { data: typeof newsMatrix }) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 relative">
      {/* Left Column - Massive Lead Story (col-span-8) */}
      <div className="lg:col-span-8 flex flex-col gap-6 order-1 border-r-0 lg:border-r border-border pr-0 lg:pr-6">
        <div className="bg-[#e9e6df] aspect-[21/9] w-full relative overflow-hidden flex items-center justify-center text-muted-foreground/50 text-xs tracking-widest font-sans uppercase">
          Lead Image
        </div>
        <div className="flex flex-col gap-4 max-w-3xl flex-1 justify-center">
          <div className="flex items-center gap-3">
            <span className="text-desk-politics font-bold text-[10px] uppercase tracking-wider">Congress</span>
          </div>
          <h2 className="font-[family-name:var(--font-playfair)] font-black text-5xl md:text-6xl leading-[1.1] tracking-tight hover:text-primary transition-colors cursor-pointer">
            <Link href={`/${data.leadStory.desk.toLowerCase()}/${data.leadStory.slug}`}>
              {data.leadStory.title}
            </Link>
          </h2>
          <p className="text-xl text-foreground/80 leading-relaxed font-serif mt-2">
            {data.leadStory.excerpt}
          </p>
        </div>
      </div>

      {/* Right Column - Stacked Secondary Stories (col-span-4) */}
      <div className="lg:col-span-4 flex flex-col gap-6 order-2">
        {data.secondaryStories.slice(2, 5).map((story, idx) => (
          <article key={idx} className="border-b border-border pb-6 flex flex-col gap-2">
            <span className="uppercase text-[10px] font-bold tracking-wider text-desk-business">{story.desk}</span>
            <h3 className="font-serif font-bold text-2xl leading-tight hover:underline cursor-pointer">
              <Link href={`/${story.desk.toLowerCase()}/${story.slug}`}>
                {story.title}
              </Link>
            </h3>
            <p className="text-sm text-muted-foreground line-clamp-2 mt-1">
              {story.excerpt}
            </p>
            <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground font-sans">
              <span>{story.timeAgo}</span>
              {story.readTime && (
                <>
                  <span className="text-muted-foreground mx-1">•</span>
                  <span>{story.readTime}</span>
                </>
              )}
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}

// Extracted Sidebars for reuse
function BorgRecordSidebar() {
  return (
    <div className="bg-primary/5 border border-primary/20 p-5 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <h2 className="font-sans uppercase font-bold text-sm tracking-wider text-primary">The Borg Record</h2>
        <div className="w-2 h-2 rounded-full bg-destructive animate-pulse"></div>
      </div>

      <div className="flex flex-col gap-5">
        <div className="flex flex-col gap-1 border-b border-primary/10 pb-4">
          <span className="text-xs text-muted-foreground font-sans">Just Updated</span>
          <Link href="/borg-record/politicians/senator-smith" className="font-serif font-bold text-lg hover:text-primary leading-tight">
            Senator Jane Smith (D-NY) Promise Tracker Adjusted
          </Link>
          <span className="inline-flex mt-1 text-[10px] items-center text-destructive font-bold uppercase tracking-wider">
            Status: Broken
          </span>
        </div>
        <div className="flex flex-col gap-1 border-b border-primary/10 pb-4">
          <span className="text-xs text-muted-foreground font-sans">Key Vote Added</span>
          <Link href="/borg-record/votes/hr-4521" className="font-serif font-bold text-lg hover:text-primary leading-tight">
            H.R. 4521: Clean Energy Procurement Act
          </Link>
          <p className="text-sm text-muted-foreground mt-1 line-clamp-2">Complete roll call data now available in the public grid.</p>
        </div>
        <Link href="/borg-record" className="w-full text-center text-sm font-bold font-sans uppercase tracking-wider border border-primary text-primary py-2 mt-2 hover:bg-primary hover:text-primary-foreground transition-colors group flex items-center justify-center gap-2">
          Access Full Database <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
        </Link>
      </div>
    </div>
  );
}

function NewsletterSidebar() {
  return (
    <div className="bg-foreground text-background p-6 rounded-sm mt-4">
      <h3 className="font-serif font-bold text-2xl mb-2">The Morning Briefing</h3>
      <p className="text-sm text-background/80 mb-4">Unfiltered intelligence from the grid, delivered daily.</p>
      <div className="flex flex-col gap-2">
        <input type="email" placeholder="Your email address" className="bg-background/10 border border-background/20 px-3 py-2 text-sm text-background placeholder:text-background/50 focus:outline-none focus:border-background transition-colors" />
        <button className="bg-background text-foreground font-bold font-sans uppercase tracking-wider text-sm py-2 hover:bg-background/90 transition-colors">
          Subscribe
        </button>
      </div>
    </div>
  );
}

// MAIN PAGE COMPONENT
export default async function Home() {
  // Algorithmic Layout Engine Implementation
  // ---------------------------------------
  // The layout is determined dynamically based on three primary drivers:
  // 1. News Severity (Primary)
  // 2. Media Quality (Secondary)
  // 3. Time of Day Edition (Tertiary)

  let activeLayout = 'standard'; // Default safe layout
  let currentEdition = "Morning Briefing";

  // Simulate server time (mocking current time of day)
  const currentHour = new Date().getHours();
  const isEveningEdition = currentHour >= 18 || currentHour < 6; // 6 PM to 6 AM

  if (isEveningEdition) {
    currentEdition = "Evening Edition";
    activeLayout = 'hero_focus'; // Evening defaults to magazine style
  } else {
    currentEdition = "Morning Briefing";
    activeLayout = 'standard'; // Morning defaults to dense grid
  }

  // Override logic based on Content payload
  if (newsMatrix.leadStory.severity === 5) {
    // Earth-shattering news forces the Hero Layout regardless of time
    activeLayout = 'hero_focus';
  } else if (!newsMatrix.leadStory.hasHighResHero && activeLayout === 'hero_focus') {
    // If we wanted Hero Focus but don't have good art, fallback to standard
    activeLayout = 'standard';
  }

  // To prove it works, we can simulate different scenarios by changing the mock object, 
  // but the logic above securely handles the routing decision.

  return (
    <div className="flex flex-col min-h-screen relative">
      <main className="flex-1 max-w-[1400px] w-full mx-auto px-4 md:px-6 py-8">

        {/* Edition Indicator (Optional visual cue that algorithm is working) */}
        <div className="mb-4 flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-destructive animate-pulse"></span>
          <span className="font-sans text-xs font-bold uppercase tracking-widest text-muted-foreground">
            Algorithmic Matrix Active — {currentEdition}
          </span>
        </div>

        {/* Dynamic Layout Switcher */}
        {activeLayout === 'standard' ? (
          <StandardNewspaperLayout data={newsMatrix} />
        ) : (
          <HeroFocusLayout data={newsMatrix} />
        )}

      </main>
    </div>
  );
}
