export default function TermsPage() {
    return (
        <div className="container max-w-[900px] mx-auto px-4 py-16 md:py-24">
            <div className="space-y-12">
                <header className="space-y-6 border-b-4 border-foreground pb-8">
                    <h1 className="font-[family-name:var(--font-playfair)] text-5xl md:text-7xl font-black tracking-tight uppercase leading-none">
                        Terms of Service
                    </h1>
                    <p className="font-[family-name:var(--font-source-sans)] text-xl font-semibold uppercase tracking-widest text-muted-foreground">
                        Broadcast Utilization Agreement
                    </p>
                </header>

                <article className="prose prose-lg dark:prose-invert font-[family-name:var(--font-source-sans)] text-foreground prose-headings:font-[family-name:var(--font-playfair)] prose-headings:font-black pb-16">
                    <p className="lead text-2xl font-[family-name:var(--font-playfair)] text-muted-foreground leading-relaxed">
                        By accessing the broadcast terminal of The Daily Borg, you consent to the operational parameters established herein.
                    </p>

                    <h2>1. Distribution and Syndication</h2>
                    <p>
                        All factual reporting, severity scores, and layout logic generated by The Daily Borg algorithmic engine are public domain. You are encouraged to syndicate, redistribute, and archive our broadcast transmissions. However, automated scraping must respect standard rate limits to ensure system stability.
                    </p>

                    <h2>2. System Integrity</h2>
                    <p>
                        Attempts to artificially manipulate the algorithmic layout engine, artificially inflate severity scores, or execute Denial of Service (DoS) attacks against the Broadcast Grid will result in immediate network-level bans.
                    </p>

                    <h2>3. Algorithmic Disclaimer</h2>
                    <p>
                        The Daily Borg utilizes AI ingestion models to parse and classify raw news events. While our models are tested for absolute zero-bias and factual consistency, anomalies may occur. Readers are encouraged to verify cross-referenced sources linked within the "Borg Record" tabs.
                    </p>

                    <h2>4. Modifications to the Grid</h2>
                    <p>
                        We reserve the right to modify the visual presentation, layout logic, or algorithmic severity thresholds without prior system-wide notice. The Grid is a living system.
                    </p>

                    <div className="p-6 bg-muted border-l-4 border-foreground mt-12">
                        <p className="m-0 text-sm font-bold uppercase tracking-widest">
                            Effective Date: Version 2026.04.1
                        </p>
                    </div>
                </article>
            </div>
        </div>
    );
}
